---
name: Build & Push to Octopus

on:
  push:

env:
  MASTER_BRANCH: master

jobs:
  build:
    name: Build Image and Push to Octo
    runs-on: [eks]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Lazy Setup
        uses: variant-inc/actions-setup@v1
        id: lazy-setup

      - name: Lazy Action Octopus
        uses: variant-inc/actions-octopus@v1
        with:
          default_branch: ${{ env.MASTER_BRANCH }}
          version: ${{ steps.lazy-setup.outputs.image_version }}
